"""
Caffeine Chronicles — Local Fact Bank
370 coffee/caffeine facts + 55 coffee shop recommendations.
"""

FACTS = [
    # ── History & Origins ────────────────────────────────────────────────
    "Legend says coffee was discovered by an Ethiopian goat herder named Kaldi after his goats started dancing from eating coffee berries.",
    "The word 'coffee' comes from the Arabic 'qahwah,' which originally referred to a type of wine.",
    "Coffee was banned in Mecca in 1511 because leaders believed it stimulated radical thinking.",
    "The first coffeehouse in Europe opened in Venice in 1629, and they were called 'penny universities' in England because a cup cost one penny.",
    "King Charles II tried to ban coffeehouses in 1675, fearing they were hotbeds of political rebellion.",
    "The Boston Tea Party of 1773 made coffee the patriotic drink of choice in America.",
    "Ottoman law once allowed a woman to divorce her husband if he failed to provide her with enough coffee.",
    "Pope Clement VIII reportedly baptized coffee in 1600 after his advisors called it 'Satan's drink.'",
    "The first webcam was invented at Cambridge University to monitor a coffee pot so researchers wouldn't walk to an empty machine.",
    "Brazil has been the world's largest coffee producer for over 150 years straight.",
    "Coffee wasn't always a drink — East African tribes once mixed coffee berries with animal fat to create energy balls.",
    "The term 'cup of joe' may come from Secretary of the Navy Josephus Daniels, who banned alcohol on ships in 1914.",
    "Frederick the Great of Prussia tried to ban coffee in 1777, insisting that people drink beer instead.",
    "The Dutch were the first Europeans to cultivate coffee commercially, starting in the 1600s in their colonies.",
    "Lloyds of London, the famous insurance market, started as a coffeehouse in 1688.",
    "Bach wrote a comedic cantata in 1735 about a woman addicted to coffee whose father tries to make her stop.",
    "The French philosopher Voltaire reportedly drank 40 to 50 cups of coffee per day.",
    "Coffee cultivation spread to the Americas thanks to a single plant smuggled from France to Martinique in 1723.",
    "The first instant coffee was invented by Japanese-American chemist Satori Kato in 1901.",
    "During the Civil War, Union soldiers were given coffee as part of their rations — roughly 36 pounds per year per soldier.",
    "The coffee break became an official workplace tradition in the United States during the 1950s.",
    "Finland consumes the most coffee per capita in the world, averaging about 12 kg per person per year.",
    "George Washington invented a mass-produced instant coffee in 1910 — not the president, but a Belgian-American inventor.",
    "The espresso machine was invented in Italy in 1884 by Angelo Moriondo to speed up coffee service for customers.",
    "Coffee reached Japan in the 1700s through Dutch traders in Nagasaki, but didn't become popular until the 1900s.",

    # ── Science & Biology ────────────────────────────────────────────────
    "Caffeine takes only about 10 minutes to start affecting your body after you drink a cup of coffee.",
    "Coffee is the second most traded commodity on Earth by monetary value, right behind crude oil.",
    "A coffee bean is actually the seed inside a bright red fruit called a coffee cherry.",
    "There are over 1,000 chemical compounds in a roasted coffee bean — more than in wine.",
    "Caffeine works by blocking adenosine receptors in your brain, which are responsible for making you feel sleepy.",
    "The lethal dose of caffeine is roughly 10 grams, equivalent to drinking about 80 to 100 cups of coffee at once.",
    "Dark roast coffee actually has slightly less caffeine than light roast because roasting burns off some caffeine.",
    "Coffee plants can live for over 100 years, but they produce the most fruit between ages 7 and 20.",
    "Caffeine is found in over 60 different plant species, not just coffee — including tea, cacao, and kola nuts.",
    "Your body develops a tolerance to caffeine in just 1 to 4 days of regular consumption.",
    "Decaf coffee isn't 100% caffeine-free — a typical cup still contains about 2 to 15 milligrams of caffeine.",
    "It takes approximately 70 coffee beans to make one cup of coffee.",
    "Caffeine reaches peak levels in your bloodstream within 30 to 60 minutes of consumption.",
    "The half-life of caffeine in the human body is about 5 hours, meaning half of it is still in your system 5 hours later.",
    "Coffee grounds can absorb odors, which is why some people use them as natural deodorizers.",
    "Robusta coffee beans contain about twice as much caffeine as Arabica beans.",
    "A coffee tree produces about one to two pounds of roasted coffee per year.",
    "The two main species of coffee are Arabica (about 60-70% of production) and Robusta (about 30-40%).",
    "Caffeine is a natural pesticide — plants evolved it to paralyze and kill insects that try to eat them.",
    "Your liver metabolizes caffeine using the enzyme CYP1A2, and genetic variations make some people process it much faster.",
    "Coffee contains antioxidants that can help fight inflammation and protect cells from damage.",
    "Bees can detect caffeine in flower nectar, and it actually helps them remember which flowers to revisit.",
    "The aroma of coffee is produced by over 800 volatile compounds released during roasting.",
    "Caffeine can improve athletic performance by up to 12% by increasing adrenaline levels.",
    "Coffee is technically a fruit juice since it's made from the seeds of the coffee cherry fruit.",
    "The acidity of black coffee is about pH 5, which is less acidic than orange juice or most sodas.",
    "Humans are one of only a few species that actively seek out caffeine for its stimulant effects.",
    "Drinking coffee can temporarily raise your metabolic rate by 3 to 11 percent.",
    "The caffeine in a cup of coffee can improve your reaction time by about 10 percent.",
    "Caffeine withdrawal is recognized as a clinical syndrome and typically peaks 24 to 48 hours after your last cup.",

    # ── Production & Processing ──────────────────────────────────────────
    "It takes about 5 years for a coffee plant to produce its first crop of cherries.",
    "Coffee beans are typically roasted at temperatures between 370°F and 540°F (188°C to 282°C).",
    "The 'coffee belt' — the region where coffee grows best — spans the tropics between the Tropics of Cancer and Capricorn.",
    "Kopi luwak, made from beans eaten and excreted by civets, can cost over $600 per pound.",
    "It takes about 2,500 coffee cherries to produce a single pound of roasted coffee.",
    "There are two main methods of processing coffee: the 'washed' method and the 'natural' (dry) method.",
    "Ethiopia alone has an estimated 6,000 to 10,000 varieties of wild coffee plants.",
    "Vietnam is the world's second largest coffee producer and the biggest exporter of Robusta beans.",
    "Coffee roasting causes the Maillard reaction — the same chemical process that makes bread golden and steak brown.",
    "Green (unroasted) coffee beans can be stored for up to a year without losing significant quality.",
    "The 'first crack' during roasting happens when beans reach about 385°F and expand like popcorn.",
    "Colombia produces about 12% of the world's coffee and is famous for its mild, well-balanced Arabica beans.",
    "Hawaii is the only U.S. state that commercially grows coffee, and Kona coffee is its most famous variety.",
    "Shade-grown coffee supports biodiversity because the tree canopy provides habitat for birds and insects.",
    "About 25 million smallholder farmers produce 80% of the world's coffee supply.",
    "The coffee fruit is sometimes dried and brewed into a tea called 'cascara,' meaning 'husk' in Spanish.",
    "A single coffee plant can produce enough beans for about one to one-and-a-half pounds of roasted coffee per year.",
    "Coffee beans expand by about 50 to 100% of their original size during the roasting process.",
    "Jamaica Blue Mountain coffee is one of the most expensive in the world, often selling for over $65 per pound.",
    "The 'Swiss Water Process' decaffeinates coffee using only water and osmosis — no chemicals involved.",

    # ── Culture & Fun Facts ──────────────────────────────────────────────
    "In Italy, ordering a 'latte' will just get you a glass of milk — you need to say 'caffè latte.'",
    "The world's most expensive coffee, Black Ivory, costs over $1,000 per pound and is processed through elephants.",
    "Finns consume so much coffee that the average adult drinks about 4 cups per day.",
    "In Turkey, the groom's ability to make good coffee was historically considered in marriage decisions.",
    "Japan has more than 150,000 coffee shops, and canned coffee from vending machines outsells fresh-brewed.",
    "The largest cup of coffee ever brewed held 22,739.14 liters and was made in Colombia in 2019.",
    "South Korea's coffee culture exploded in the 2000s, and Seoul now has more coffee shops than any other city.",
    "In Ethiopia, a traditional coffee ceremony can last two to three hours and involves roasting beans from scratch.",
    "Americans spend an average of over $1,100 per year on coffee.",
    "The flat white originated in either Australia or New Zealand in the 1980s — both countries claim credit.",
    "Starbucks opens roughly 2 new stores every single day somewhere in the world.",
    "In Sweden, 'fika' is a daily coffee break tradition that is deeply embedded in the culture and workplace.",
    "Brazil once sent its Olympic athletes to the 1932 Games in Los Angeles on a ship funded by coffee sales.",
    "Espresso literally means 'pressed out' in Italian, referring to the way water is forced through the grounds.",
    "Cold brew coffee is 67% less acidic than hot coffee because the cold extraction process produces fewer acids.",
    "An estimated 2.25 billion cups of coffee are consumed worldwide every single day.",
    "The world's oldest cat, Creme Puff, lived to 38 years old and reportedly drank coffee every morning.",
    "Vietnamese coffee is traditionally brewed with a small metal drip filter called a 'phin' right at the table.",
    "The first coffeehouse in the United States opened in Boston in 1676.",
    "In Cuba, coffee is traditionally brewed very strong and sweet, served in tiny cups called 'tacitas.'",
    "The cappuccino gets its name from the Capuchin monks, whose brown robes match the color of the drink.",
    "Ireland's traditional Irish coffee — coffee, whiskey, sugar, and cream — was invented in 1943 at a Shannon Airport bar.",
    "There are roughly 38 different sizes and names for coffee drinks at major chains worldwide.",
    "The average barista in a specialty coffee shop makes about 200 espresso drinks per shift.",
    "Adding milk to your coffee was first popularized in France in the 1680s.",

    # ── Health & Body ────────────────────────────────────────────────────
    "Moderate coffee consumption (3 to 5 cups/day) is associated with a lower risk of type 2 diabetes.",
    "Coffee contains magnesium, potassium, and niacin — essential minerals your body needs every day.",
    "Studies suggest regular coffee drinkers have a 26% lower risk of developing colorectal cancer.",
    "Caffeine can constrict blood vessels, which is why it's an ingredient in some headache medications.",
    "Drinking coffee before a nap — a 'coffee nap' — can make you more alert because caffeine kicks in as you wake.",
    "Pregnant women are generally advised to limit caffeine to 200 mg per day, about one 12-ounce cup.",
    "Coffee consumption has been linked to a lower risk of Parkinson's disease in multiple large studies.",
    "The smell of coffee alone can reduce stress — a study found that the aroma changes brain proteins linked to stress.",
    "Regular coffee drinkers have a lower risk of developing Alzheimer's disease, according to several studies.",
    "Caffeine can increase dopamine production in the brain, which is partly why coffee makes you feel good.",
    "A study found that people who drink 3 to 4 cups of coffee daily have a 19% reduced risk of dying from heart disease.",
    "Coffee is the single largest source of antioxidants in the typical Western diet.",
    "Caffeine can temporarily increase your blood pressure by 3 to 5 points, especially if you're not a regular drinker.",
    "The stimulating effects of caffeine wear off completely within about 8 to 10 hours for most people.",
    "Coffee may improve long-term memory — a study found that 200 mg of caffeine helped consolidate memories.",
    "People who metabolize caffeine slowly are more likely to experience anxiety and sleep disruption from coffee.",
    "Coffee contains soluble fiber — about 1 gram per cup — which can support digestive health.",
    "Drinking coffee 30 minutes before exercise can increase fat burning during your workout.",
    "The European Food Safety Authority considers up to 400 mg of caffeine per day safe for most adults.",
    "Studies show coffee drinkers tend to live longer on average, though the exact reasons are still debated.",

    # ── Weird & Wonderful ────────────────────────────────────────────────
    "Coffee grounds can be used to grow mushrooms because spent grounds are rich in nutrients fungi love.",
    "There is a spa in Japan where you can bathe in a giant pool filled with warm coffee.",
    "NASA-funded research found that spiders on caffeine build the most erratic and disorganized webs.",
    "Some car manufacturers have experimented with using coffee chaff (husks) as a material for car parts.",
    "Coffee is so important to Brazil's identity that the word 'breakfast' in Portuguese is 'café da manhã' — morning coffee.",
    "A study found that the smell of coffee is the second most recognizable scent in America, after burning wood.",
    "There's a coffee variety called 'Geisha' (or 'Gesha') from Ethiopia that can sell for over $100 per cup at auction.",
    "You can waterproof fabric using old coffee grounds — they contain natural oils that repel water.",
    "In 2015, a British bus company ran a fleet powered partly by biofuel made from used coffee grounds.",
    "Coffee grounds make an excellent exfoliant for skin because the texture is abrasive but not harsh.",
    "Beethoven was so obsessive about his coffee that he counted exactly 60 beans per cup, every single time.",
    "The International Space Station has a specially designed espresso machine called ISSpresso.",
    "Coffee-flavored postage stamps were released by Brazil in 2001 — they actually smelled like coffee.",
    "There is a species of bat in Central America that eats coffee cherries and helps spread coffee plants.",
    "A coffee company in Finland created the world's first coffee-powered car that ran on coffee chaff briquettes.",
    "Theodore Roosevelt reportedly drank a gallon of coffee a day and is credited with coining 'Good to the last drop.'",
    "Scientists have discovered that coffee waste can be converted into biodiesel fuel.",
    "The most caffeinated coffee in the world, 'Devil Mountain Black Label,' has about 1,555 mg of caffeine per 12 oz serving.",
    "In the 17th century, women in England petitioned against coffee, claiming it made their husbands less energetic at home.",
    "You can dye fabric, paper, and even Easter eggs using brewed coffee as a natural dye.",
    "There's a museum in Vienna, Austria entirely dedicated to coffee — the Kaffeemuseum.",
    "Coffee cherries were once fermented into a type of wine by Ethiopian communities before brewing was invented.",
    "The world barista championship requires competitors to prepare 12 drinks in just 15 minutes.",
    "Some coffee farmers use coffee pulp as organic fertilizer, recycling it back into the soil.",
    "A single espresso shot has less caffeine than a cup of drip coffee — about 63 mg vs. 95 mg.",

    # ── Economics & Industry ─────────────────────────────────────────────
    "The global coffee industry employs over 125 million people worldwide across the supply chain.",
    "Starbucks buys approximately 3% of the entire world's coffee supply each year.",
    "The specialty coffee market is growing at about 12% per year, much faster than commodity coffee.",
    "A typical coffee farmer earns less than $2 per pound of coffee cherries in many producing countries.",
    "Fair Trade certification guarantees coffee farmers a minimum price of $1.40 per pound of green coffee.",
    "The average American coffee drinker spends about $20 per week on coffee drinks.",
    "Coffee vending machines in Japan alone generate over $5 billion in revenue annually.",
    "Brazil produces about one-third of all coffee grown on Earth — roughly 60 million bags per year.",
    "The New York Coffee Exchange was established in 1882 and remains the primary market for trading coffee futures.",
    "About 65% of coffee consumed in America is drunk during breakfast hours.",
    "Instant coffee makes up over 50% of the coffee consumed in some countries, including the UK and Australia.",
    "The 'third wave' coffee movement treats coffee like wine — focusing on origin, processing, and flavor profiles.",
    "Coffee is grown in over 70 countries, but just 5 of them produce more than 65% of the world's supply.",
    "The average American drinks about 3 cups of coffee per day.",
    "A single Starbucks Grande latte requires about 100 coffee beans to make.",

    # ── Brewing & Preparation ────────────────────────────────────────────
    "The ideal water temperature for brewing coffee is between 195°F and 205°F (90°C to 96°C).",
    "French press coffee contains more cafestol, a compound that can slightly raise cholesterol, than filtered coffee.",
    "The pour-over method was invented by a German housewife named Melitta Bentz in 1908 using blotting paper.",
    "Espresso is brewed at about 9 bars of pressure — that's 9 times the atmospheric pressure at sea level.",
    "Cold brew requires 12 to 24 hours of steeping time, while espresso takes only 25 to 30 seconds.",
    "The AeroPress was invented in 2005 by Alan Adler, who also invented the Aerobie flying disc.",
    "Turkish coffee is one of the oldest methods of preparation, dating back to the 15th century.",
    "The Chemex coffee maker was invented in 1941 and is part of the permanent collection at MoMA.",
    "Siphon (vacuum) coffee makers use vapor pressure to brew and have been around since the 1840s.",
    "The moka pot, invented by Alfonso Bialetti in 1933, is found in about 90% of Italian households.",
    "Pre-ground coffee loses about 60% of its aroma within 15 minutes of being ground.",
    "The strength of your coffee depends more on the coffee-to-water ratio than the roast level.",
    "Blooming — pre-wetting grounds with a small amount of water — releases CO2 and improves extraction.",
    "A burr grinder produces a more consistent grind than a blade grinder, which makes a noticeable difference in taste.",
    "Brewing coffee with water that's too hot (over 205°F) extracts bitter compounds and ruins the flavor.",

    # ── Geography & Varieties ────────────────────────────────────────────
    "Yemen was the first country to cultivate coffee commercially, starting around the 15th century.",
    "Costa Rica banned the growing of low-quality Robusta beans in 1989 to protect its Arabica reputation.",
    "Indonesia's Sulawesi Toraja coffee is aged in the tropical climate, giving it an earthy, spicy flavor.",
    "Panama Gesha coffee has sold at auction for over $2,500 per pound, making it one of the priciest coffees on Earth.",
    "The island of Saint Helena in the South Atlantic produces one of the rarest coffees in the world.",
    "Rwanda's coffee industry was rebuilt after the 1994 genocide and is now a major source of national income.",
    "Indian Monsooned Malabar coffee is exposed to monsoon winds for 3 to 4 months to mellow its flavor.",
    "Coffee grown at higher altitudes — above 4,000 feet — tends to be denser, harder, and more flavorful.",
    "Guatemala's Antigua region produces coffee prized for its rich, chocolatey flavor due to volcanic soil.",
    "The island of Java in Indonesia was once so famous for coffee that 'java' became slang for the drink itself.",

    # ── Sustainability & Environment ─────────────────────────────────────
    "Climate change could reduce suitable coffee-growing land by up to 50% by 2050.",
    "An estimated 16 billion disposable coffee cups are thrown away globally every year.",
    "Recycled coffee grounds are being used to create sustainable building materials like bricks.",
    "A single cup of coffee requires about 140 liters of water to produce, from growing to brewing.",
    "Shade-grown coffee farms can support up to 150 species of birds, compared to almost none on sun-grown plantations.",
    "Used coffee grounds can improve garden soil because they add nitrogen as they decompose.",
    "Some companies are now making sunglasses, furniture, and even 3D-printing material from recycled coffee grounds.",
    "Reusable coffee cups need to be used at least 15 to 20 times to offset their environmental footprint.",
    "Arabica coffee is especially vulnerable to climate change because it requires very specific growing conditions.",
    "Coffee leaf rust, a fungal disease, has devastated crops in Central America, destroying up to 70% in some regions.",

    # ── Caffeine in Other Things ─────────────────────────────────────────
    "A typical cup of green tea has about 28 mg of caffeine — roughly a third of what's in a cup of coffee.",
    "Dark chocolate contains about 12 mg of caffeine per ounce, while milk chocolate has only about 6 mg.",
    "A can of cola has about 34 mg of caffeine — about a third of a typical cup of coffee.",
    "Some over-the-counter pain relievers contain up to 130 mg of caffeine per dose to enhance effectiveness.",
    "Energy drinks typically contain between 80 and 300 mg of caffeine, depending on the brand and size.",
    "Yerba mate, popular in South America, contains about 85 mg of caffeine per cup — similar to coffee.",
    "A standard serving of matcha has about 70 mg of caffeine, but it's released more slowly than coffee.",
    "White tea has the least caffeine of all true teas — about 15 to 30 mg per cup.",
    "Guarana seeds contain about four times more caffeine by weight than coffee beans.",
    "Some bottled water brands now sell caffeinated water with about 60 mg of caffeine per bottle.",

    # ── Records & Extremes ───────────────────────────────────────────────
    "The fastest time to drink a cup of coffee is 3.17 seconds, set in a Guinness World Record.",
    "The largest iced coffee ever made was 14,228.1 liters, created in South Korea in 2014.",
    "The most expensive coffee machine for home use costs over $20,000.",
    "The longest coffee tasting session lasted over 29 hours in a Brazilian coffee event.",
    "The tallest coffee cup tower ever built was over 9 feet tall and used 2,592 cups.",
    "New Yorkers drink approximately 7 times more coffee than the average American city.",
    "The oldest known coffeehouse still in operation is Café Procope in Paris, open since 1686.",
    "The record for the most cups of coffee served in one hour by a single barista is over 360.",
    "The world's largest coffee roaster can roast 5 tons of beans in a single batch.",
    "Finland's annual coffee consumption is about 10 kg per person — more than double the American average.",

    # ── Extra Unique Facts ───────────────────────────────────────────────
    "Honeybees prefer flowers that produce nectar containing caffeine, and caffeine improves their pollination.",
    "Coffee beans are technically not beans at all — they're seeds of a berry.",
    "The 'crema' on top of an espresso is created by carbon dioxide being emulsified under high pressure.",
    "In space, astronauts drink coffee from special pouches through straws because liquids float in microgravity.",
    "A study found that the optimal time to drink coffee is between 9:30 and 11:30 AM based on cortisol rhythms.",
    "The Sumatran coffee process called 'wet-hulling' gives beans their distinctive earthy, herbal flavor.",
    "George Clooney's Nespresso endorsement deal is reportedly worth about $40 million.",
    "Coffee cupping — the professional tasting method — involves slurping coffee loudly from a spoon.",
    "The world drinks about 500 billion cups of coffee per year, making it one of the most popular beverages.",
    "Coffee plants produce white, fragrant flowers that smell like jasmine before they develop cherries.",
    "Norwegian explorer Roald Amundsen brought large supplies of coffee on his expedition to the South Pole.",
    "The 'angel's share' in coffee roasting refers to the weight lost (about 12-20%) as moisture evaporates.",
    "A study found that smelling coffee without drinking it can still improve cognitive performance.",
    "Instant coffee was popularized during World War II when it was included in soldiers' ration kits.",
    "Coffee vending machines were first introduced in the United States in the 1940s.",
    "In some regions of Mexico, coffee is served with cinnamon and raw sugar as 'café de olla' in a clay pot.",
    "The coffee cherry's outer fruit can be eaten and has a mildly sweet taste similar to cranberries.",
    "There's a coffee species called Coffea stenophylla that tastes like Arabica but can grow in warmer climates.",
    "A 'ristretto' is a shorter espresso shot using the same amount of coffee but half the water.",
    "Nescafé was invented in 1938 after the Brazilian government asked Nestlé to find a solution for excess coffee.",
    "The tradition of 'latte art' started in Italy in the 1980s and became popular in the U.S. in the 1990s.",
    "Your genes determine how fast you metabolize caffeine — some people are up to 40 times faster than others.",
    "A coffee taster at a large company may sample over 300 cups of coffee per day.",
    "In Ethiopia, the birthplace of coffee, it is considered rude to refuse a cup offered by a host.",
    "The Portuguese word for coffeehouse — 'cafeteria' — gave English the word 'cafeteria.'",
    "Black coffee has only about 2 calories per 8-ounce cup, making it one of the lowest-calorie beverages.",
    "Scientists have sequenced the entire genome of the Coffea canephora (Robusta) coffee plant.",
    "An 'affogato' is an Italian dessert made by pouring a shot of hot espresso over vanilla gelato.",
    "Coffee trees produce fruit for about 25 to 30 years before their yield significantly decreases.",
    "The Vietnamese egg coffee — cà phê trứng — uses whipped egg yolk as a creamy topping.",
    "A mechanical coffee grinder was invented in the 1600s in England, replacing the mortar and pestle.",
    "The longest-running scientific study on coffee's health effects has been tracking participants for over 30 years.",
    "Coffee residue in ancient pottery has helped archaeologists date trade routes in the Middle East.",
    "A Brazilian farmer named Francisco de Melo Palheta smuggled coffee seeds out of French Guiana in 1727 in a bouquet.",
    "The word 'barista' is Italian for 'bartender' and wasn't commonly used in English until the 1980s.",
    "Thailand's northern highlands now produce award-winning specialty coffee, rivaling established origins.",
    "There are about 124 known species in the Coffea genus, but only 2 are commercially significant.",
    "The coffee cherry's mucilage — the sticky layer around the bean — is sometimes called 'honey' in processing.",
    "Professional coffee graders can identify the country of origin, altitude, and process by taste alone.",
    "A shot of espresso has about 63 mg of caffeine, while a 16 oz drip coffee can have over 300 mg.",
    "In the 18th century, coffee was sometimes prescribed by doctors as a cure for ailments including headaches.",
    "Adding a pinch of salt to coffee grounds before brewing can reduce bitterness.",
    "Coffee futures are traded on the ICE exchange in New York and can influence prices farmers receive worldwide.",
    "There's a coffee tradition in Scandinavia called 'kaffeost' where cheese curds are placed in the coffee cup.",
    "The Ethiopian coffee ceremony symbolizes friendship and respect, and it is rude to leave before three cups.",
    "A cortado — espresso cut with a small amount of warm milk — originated in Spain's Basque Country.",
]

COFFEE_SHOPS = [
    "The Elephant House in Edinburgh, Scotland, is famous as the café where J.K. Rowling wrote early chapters of Harry Potter while sipping coffee.",
    "Cafe Central in Vienna, Austria, has been serving coffee since 1876 and was a hangout for Sigmund Freud and Leon Trotsky.",
    "Blue Bottle Coffee in Oakland, California, started in a tiny shed and became one of the world's most influential specialty roasters.",
    "Tomoca Coffee in Addis Ababa, Ethiopia, has served traditional Ethiopian coffee since 1953 and is a pilgrimage site for coffee lovers.",
    "Café de Flore in Paris, France, has been an iconic literary café since 1887, frequented by Sartre and Simone de Beauvoir.",
    "Fuglen in Tokyo, Japan, is a Norwegian-Japanese café serving Scandinavian-style specialty coffee in the trendy Tomigaya neighborhood.",
    "% Arabica in Kyoto, Japan, sits beside a traditional Japanese temple and is known for minimalist design and world-class lattes.",
    "Truth Coffee Roasting in Cape Town, South Africa, is steampunk-themed and was named the best coffee shop in the world by The Telegraph.",
    "Café Tortoni in Buenos Aires, Argentina, has been open since 1858 and is the city's oldest and most famous coffeehouse.",
    "Tim Wendelboe in Oslo, Norway, is a tiny micro-roastery run by a world barista champion, serving some of Scandinavia's finest cups.",
    "Stumptown Coffee Roasters in Portland, Oregon, helped kickstart the third wave coffee movement in the United States.",
    "Café Kopi Luwak in Bali, Indonesia, lets visitors see the civet cat process firsthand and taste the famous (and controversial) brew.",
    "The Barn in Berlin, Germany, is a minimalist roastery known for extremely light roasts that highlight single-origin flavors.",
    "Intelligentsia Coffee in Chicago, Illinois, pioneered 'direct trade' relationships with coffee farmers worldwide.",
    "Roscioli Caffè Pasticceria in Rome, Italy, combines world-class espresso with traditional Roman pastries near Campo de' Fiori.",
    "Revolver Coffee in Vancouver, Canada, rotates guest roasters from around the world so the menu changes constantly.",
    "Café Hawelka in Vienna, Austria, is a bohemian institution open since 1939, famous for its late-night Buchteln pastries and melange coffee.",
    "Proud Mary in Melbourne, Australia, is a pioneer of the city's legendary coffee scene with ambitious single-origin offerings.",
    "Finca Lerida in Boquete, Panama, is a coffee estate where you can tour the plantation and drink Gesha coffee at the source.",
    "Heart Coffee Roasters in Portland, Oregon, specializes in Nordic-style light roasts and has won numerous national awards.",
    "Bonanza Coffee Roasters in Berlin, Germany, is one of Europe's most respected specialty roasters with direct farm partnerships.",
    "Onibus Coffee in Tokyo, Japan, operates out of a converted house in Nakameguro with standing room only and exceptional filter coffee.",
    "Pergamino Café in Medellín, Colombia, is run by a coffee-growing family and serves beans from their own nearby farms.",
    "La Colombe Coffee Roasters in Philadelphia, Pennsylvania, is known for its draft lattes on tap and stunning café architecture.",
    "Sightglass Coffee in San Francisco, California, roasts beans in a converted warehouse with floor-to-ceiling windows.",
    "Fazenda Santa Margarida in São Paulo, Brazil, offers plantation tours and tastings of coffee grown right on the estate.",
    "Pelican Coffee in Hong Kong serves specialty coffee in the heart of the city's bustling Central district.",
    "The Coffee Collective in Copenhagen, Denmark, is a farmer-owned cooperative café that shares profits directly with growers.",
    "Verve Coffee Roasters in Santa Cruz, California, is known for sourcing high-altitude beans and their beachside flagship café.",
    "Café Régua in Lisbon, Portugal, is a tiny specialty shop in the Mouraria neighborhood with single-origin Portuguese-roasted beans.",
    "Coutume Café in Paris, France, brought third wave specialty coffee to the traditionally espresso-focused French capital.",
    "Mambocino Coffee in Istanbul, Turkey, bridges traditional Turkish coffee culture with modern specialty techniques.",
    "Forty Hands in Singapore is a beloved brunch café credited with helping ignite Singapore's specialty coffee boom.",
    "Workshop Coffee in London, England, is a Clerkenwell-based roaster known for meticulous sourcing and bright, clean cup profiles.",
    "Campos Coffee in Sydney, Australia, has been a staple of the city's coffee scene since 2002 with its famous Superior Blend.",
    "Gardelli Specialty Coffees in Forlì, Italy, is run by a world coffee roasting champion and ships beans globally.",
    "Six Depot Roastery & Café in West Stockbridge, Massachusetts, is a small-town gem producing world-class micro-roasted coffee.",
    "Madal Café in Budapest, Hungary, serves Ethiopian specialty coffee in a beautifully restored historic building.",
    "Common Man Coffee Roasters in Singapore is a spacious warehouse café with an in-house roastery and training academy.",
    "Ceremonial Coffee Roasters in Annapolis, Maryland, offers immersive coffee experiences inspired by Ethiopian coffee ceremonies.",
    "Kakalove Café in Taipei, Taiwan, focuses on hand-drip single-origin coffees in a cozy, wood-paneled space.",
    "Cafeoteca in San José, Costa Rica, is a nonprofit café that showcases the country's diverse micro-lot coffees.",
    "Passenger Coffee in Lancaster, Pennsylvania, is a small-batch roaster in a restored tobacco warehouse.",
    "Satan's Coffee Corner in Barcelona, Spain, is a rebellious specialty café known for creative drinks and a no-Wi-Fi policy.",
    "Kaffa Roastery in Helsinki, Finland, hand-roasts beans in small batches in the coffee-obsessed Finnish capital.",
    "Market Lane Coffee in Melbourne, Australia, operates out of the historic Queen Victoria Market with a farm-to-cup philosophy.",
    "Hacienda Venecia in Manizales, Colombia, lets visitors stay overnight on a working coffee farm and pick cherries at sunrise.",
    "Drip Coffee in Chiang Mai, Thailand, highlights northern Thai highland beans in a relaxed tropical garden setting.",
    "Kontakt Roastery in Bratislava, Slovakia, is a small but mighty roaster putting Central European specialty coffee on the map.",
    "Roots Coffee Roaster in Bangkok, Thailand, champions Thai-grown coffee and is helping build the country's specialty scene.",
    "Reykjavik Roasters in Reykjavik, Iceland, hand-roasts beans in a cozy café decorated with vintage Icelandic furniture.",
    "Nano Kafe in Prague, Czech Republic, is a micro-café barely fitting 6 people but producing exceptional espresso.",
    "Hansa Coffee Roasters in Moshi, Tanzania, roasts Kilimanjaro-grown beans and offers tours to nearby coffee farms.",
    "Cabinet Café in Melbourne, Australia, is tucked inside a tiny heritage building and serves competition-quality espresso.",
    "Café du Monde in New Orleans, Louisiana, has served its famous chicory coffee and beignets 24/7 since 1862.",
]
